name: My Workflow
on:
  push:
    paths:
      - 'nestedActionTest/nestedHelloWorld/**' # Path filter for triggering the workflow only on changes to files in the subdirectory
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Deploy SAM templates
        run: |
          cd nestedActionTest/nestedHelloWorld
          sam deploy --stack-name mystack \
            --capabilities CAPABILITY_IAM \
            --region=eu-west-1 \
            --template-file template.yaml \
            --s3-bucket aws-sam-cli-managed-dev-pipeline-artifactsbucket-1hbdo0jil045z \
            --role-arn arn:aws:iam::492917996281:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-19T4NVO5DNV58
          
